<template>
    <NuxtLayout name="weblayout">
        <div class="header d-flex align-items-top justify-content-center py-1" style="background-color:#142339;">
            <div class="container mt-5 col">
                <h2 class="text-white fw-bolder display-2 mt-1">Terms of Service</h2>
                <h3 class="text-white">Introduction</h3>
                <p class="text-white">These Terms of Service (the “Terms”) apply as an agreement between any parent entity, subsidiary, affiliates, or legal entity belonging to the MoneyFlap group (also referred to in these Terms as “we”, “our”, “ours”, “us”, “MoneyFlap”) and the User (also referred to as “you”, “your” or “yours”). By using the website located at https://www.moneyflap.com, the related mobile website, and the mobile application (collectively, the “Websites”), you agree to be bound by these Terms of Service (this “Terms of Service” or “Agreement”), whether or not you register as a client of MoneyFlap ("Client"). If you wish to become a client and/or make use of the service (the “Service”), please read this Agreement. If you object to anything in this Agreement or the MoneyFlap Privacy Policy, do not use the Service.
This Agreement is subject to change by MoneyFlap at any time, effective upon posting on the relevant website. Your continued use of the Websites and the Service following MoneyFlap posting of revised terms of any section of the Agreement will constitute your express and binding acceptance of and consent to the revised Agreement.
PLEASE READ THIS AGREEMENT CAREFULLY AS IT CONTAINS IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES, AND OBLIGATIONS, INCLUDING VARIOUS LIMITATIONS AND EXCLUSIONS, AND A DISPUTE RESOLUTION CLAUSE THAT GOVERNS HOW DISPUTES WILL BE RESOLVED.</p>
                <h3 class="text-white">Electronic Agreement:</h3>
                <p class="text-white">This electronic contract sets out the legally binding terms of your use of the Websites and the Service. This Agreement may be modified by MoneyFlap from time to time, such modifications to be effective upon posting by MoneyFlap on the Websites. By accessing and/or using the Websites or becoming a client, you accept this Agreement and agree to the terms, conditions, and notices contained or referenced herein.</p>
                <h3 class="text-white">Access and Retention:</h3>
                <p class="text-white">This electronic contract sets out the legally binding terms of your use of the Websites and the Service. This Agreement may be modified by MoneyFlap from time to time, such modifications to be effective upon posting by MoneyFlap on the Websites. By accessing and/or using the Websites or becoming a client, you accept this Agreement and agree to the terms, conditions, and notices contained or referenced herein.</p>
                <h3 class="text-white">Our Products and Services:</h3>
                <p class="text-white">We provide services that include, but are not limited to:</p>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Borderless multi-currency accounts: Open global accounts from anywhere. Hold, send, receive, and exchange digital dollars (USDC), digital dollars (MFUSD), and digital euros (EURC), respectively, tied to the US account number.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Borderless savings accounts: Open a savings account on-chain backed directly by real-world government assets. Earn up to 5.4% tokenized Sukuk or US treasury yield with instant withdrawals at any time.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Borderless peer-to-peer (P2P) transfers: Send and receive money instantly from friends or anyone in our global search in 80+ countries powered by stablecoin rails.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Borderless money movements: Instantly move funds in and out of your global accounts on-chain or to bank accounts and mobile money in 65+ countries at near-zero cost—cash in and out at any MoneyGram points in 181 countries.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Borderless bill payments: Pay electricity, water, TV, and thousands of bills in over 30 countries at near-zero cost. Enable monthly reminders and automatic payments so you never miss bill due dates.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Borderless mobile top-ups: Recharge airtime and internet data for yourself and any mobile phone in 140+ countries, including exotic markets, at no extra cost.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Borderless credit cards: Create virtual and physical credit cards with no foreign transaction fees, allowing anyone to spend anywhere without hassle and high costs.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Cash-back & rewards: Earn up to 35% unlimited cash-back paid in digital dollars (USDC) on every purchase at numerous favorite brands such as Nike, Microsoft, and AliExpress.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Money management: Track your finances, make better decisions through real-time spending analytics, and block unwanted subscriptions with a few clicks.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Messaging & calling: Chat in real-time with your friends privately and in groups, share multimedia files, laugh over emojis, and calling made seamless.</p></li>
                </ul>
                <h3 class="text-white">Registration and Eligibility:</h3>
                <p class="text-white">To open a MoneyFlap Account and use our Services, you must confirm that:</p>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You are at least 18 years old;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You are a non-US and non-UK resident and citizen;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You are a citizen or resident of the jurisdictions we support;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You are not restricted or suspended to use the MoneyFlap Services;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You are not an individual blacklisted by the United Nations (UN), the European Union (EU), Bulgaria, and the United Kingdom (UK) Treasury Department or designated as a “Specially Designated National” by OFAC (Office of Foreign Assets Control of the U.S. Treasury Department) or placed on the U.S. Commerce Department’s “Denied Persons List”;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You are not a citizen or resident of a country blacklisted or sanctioned by the US Office of Foreign Assets Control (OFAC), the United Nations (UN), the European Union (EU), Bulgaria, and the United Kingdom (UK) Treasury;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You have read, understood, and agreed to all MoneyFlap legal disclosures, including the Privacy Policy and Terms of Service;</p></li>
                </ul>
                <p class="text-white">We have the right to refuse your account opening limit your access to our Services or reassess your eligibility whenever we encounter that the information/documents you provided are inaccurate or expired, and you do not comply with all legal requirements.</p>
                <h3 class="text-white">Commercial Use of Service:</h3>
                <p class="text-white">If you are using the Service and/or accessing the Websites on behalf of a company, entity, or organization (collectively, a “Subscribing Entity”), you represent and warrant that:</p>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You are an authorized representative of the Subscribing Entity, and you have the authority to bind the Subscribing Entity to this Terms of Service;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You have read and understand this Terms of Service; and</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You agree to this Terms of Service on behalf of the Subscribing Entity.</p></li>
                </ul>
                <p class="text-white">Illegal and/or unauthorized uses of the Websites include but are not limited to, browsing or downloading illegal content, collecting usernames and/or email addresses of clients by electronic or other means to send unsolicited email, unauthorized framing of or linking to the Websites, sharing or disclosing your username or password to any third party or permitting any third party to access your account, attempting to impersonate another user or person, use of the Websites in any fraudulent or misleading manner, any automated use of the system, such as scraping the Websites, automated scripts, spiders, robots, crawlers, data mining tools or the like, interfering with, disrupting, or creating an undue burden on the Websites or the networks or services connected to the Websites, and using the Websites in a manner inconsistent with any applicable laws and regulations. Illegal and/or unauthorized use of the Websites may be investigated, and appropriate legal action may be taken, including without limitation, civil, criminal, and injunctive redress. Use of the Websites and Service is with the permission of MoneyFlap, which may be revoked at any time, for any reason, in MoneyFlap’s sole discretion.</p>
                <h3 class="text-white">Deposits and Withdrawals:</h3>
                <h3 class="text-white">Deposits:</h3>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">On-ramp Fiat Currency: Once you have fully registered for a MoneyFlap Account and have verified your identity, you can top up your Account through various methods such as a traditional bank account, linking your bank account through Open Banking, mobile money account, linking your crypto wallet or exchange, and cash through MoneyGram locations. Thus, the amount in local currency you have deposited into your account will be exchanged for the corresponding amount in virtual currencies at the mid-market rates, confirming your stablecoin purchase.
The availability of these payment methods may depend on the country you are from or based in. The transaction fees and limits depend on the payment method used — we may at our sole discretion set the transaction fees or limits of your Account. Refer to our pricing page to learn more about our transaction limits and fees.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">On-Ramp Cryptocurrency: You can also directly receive crypto funds from external parties to your on-chain addresses in your account but note that we can only accept USDC (USD Coin) and EURC (Euro Coin) at this time. We may include additional digital assets in the future — please, always refer to our website to get any product updates or information about an eventual product release. Crypto transfers are irreversible — meaning that you may lose or can not recover your crypto funds when you send them to the wrong on-chain addresses. You are urged to double-review the accuracy of your details before making any crypto deposits.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Processing Times: The processing times of a deposit to your MoneyFlap Account depend on the chosen payment methods — commonly they happen in real-time and the transaction is confirmed once the balance of your account has been updated with the corresponding amount. However, we have the right to block or reject any deposit to your account, in which case we will refund the same amount to the sending account.</p></li>
                </ul>
                <h3 class="text-white">Withdrawals:</h3>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">The off-ramp to Fiat Currency Accounts: To withdraw or transfer funds out of your MoneyFlap Account, you must choose the most suitable payment methods in your country of residence that we support. At the moment, you can withdraw funds from your MoneyFlap Account to your bank or mobile money accounts and at any MoneyFlap locations. Besides, you can transfer funds to third-party bank or mobile money accounts (Refer to our supported countries for remittances). The processing times are generally instant but can be sometimes longer.In some cases, the withdrawal transactions may be blocked or canceled for adherence to our Anti-Money Laundering (AML) Policy and Financial Crime (FinCrime) Program — in case you must undergo an additional due diligence process or provide additional information about the recipient of the funds. Another important point to note is that the withdrawal transactions may be delayed because of technical issues, maintenance, or any other operational issues from our third-party payout partners. But, in those circumstances, we will inform you about the ongoing updates.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">The off-ramp to Cryptocurrency Accounts: You can also transfer funds out of your MoneyFlap Account to external crypto wallets. Please double review and confirm the details of the recipient before initiating any withdrawal — crypto transfers are irreversible, resulting in a full loss of your funds when you transfer funds to the wrong crypto addresses. MoneyFlap will not be liable for any transfer to the wrong crypto addresses and cannot recover your funds or refund you. Withdrawals are processed instantly, allowing your crypto funds to reach their destination in no time. Nevertheless, due to uncontrolled reasons such as technical and operational downtime of the public blockchain protocols we use to build our Services, the processing times may be longer or the transactions may fail. Please note that we are not liable for such delay or failure. (Refer to Risk Disclosure to learn more)</p></li>
                </ul>
                <h3 class="text-white">Transaction Fees and Limits</h3>
                <p class="text-white">We transparently publish all our transaction fees and limits on our Websites. However, our transaction fees and limits may vary to increase or decrease charges. You can always review and confirm our current transaction fees and limits before initiating any payments. In some cases, we may offer promotional fees or discounts on transactions to any users, including you. </p>
                <h3 class="text-white">General Risk Disclosure</h3>
                <p class="text-white">This general risk disclosure lists the most prevalent risks associated with holding or trading virtual assets, but the following list of risks is not exhaustive. You hereby acknowledge and accept these risks, including the unforeseen ones, use our Services at your own risk, and you will not hold MoneyFlap responsible for any irreversible and unrecoverable losses relating to these risks. </p>
                <h3 class="text-white">Blockchain Technology</h3>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">The nature of Virtual Assets may lead to an increased risk of fraudulent activities, cyberattacks, or other technological factors.
Some Virtual Assets transactions are deemed to be made when recorded on a public ledger, which is not usually the date or time that you have initiated the transaction.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Deposits, withdrawals, transfers, and any transactions in Virtual Assets may be irreversible, and any fund losses due to entering wrong addresses, and accidental or fraudulent transactions may be unrecoverable.</p></li>
                </ul>
                <h3 class="text-white">Legal and Regulatory</h3>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">Virtual Assets may not be legal tender in some jurisdictions and are not backed by any government or central bank.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">The regulatory framework of Virtual Assets varies among jurisdictions, resulting in significant regulatory uncertainty. Amendments, orders, legislative and regulatory changes, or actions relating to blockchain technology at a state, federal, or international level may adversely affect the use, transfer, exchange, and value of the Virtual Assets, restricting the provision of our Services to you.</p></li>
                </ul>
                <h3 class="text-white">Currency Fluctuations</h3>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">The value of Virtual Assets may be derived from the continued willingness of market participants to exchange Fiat currency or Virtual Assets for Virtual Assets, which may result in the potential for permanent and total loss of value of a particular Virtual Asset should the market for it disappear.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">The price of Virtual Assets may rise and fall over time, and the price may drastically fluctuate in value. Even though MoneyFlap only supports Virtual Assets called stablecoins that have the same value as some Fiat currencies such as U.S. Dollars (USD) and Euros (EUR), the price of stablecoins may fluctuate in value below the price of the Fiat currencies they are designed to track as the exchange rates of the Fiat currencies may change.</p></li>
                </ul>
                <h3 class="text-white">No investment advice, recommendations, or tax advice</h3>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">MoneyFlap does not provide investment advice. You are solely responsible for, and MoneyFlap has no involvement in, determining whether any Virtual Asset transaction, investment strategy, or related transaction is suitable for you. You are familiar with and are capable of evaluating the investment risks of Virtual Assets independently or you accept to seek legal, regulatory, business, investment, financial tax, and accounting advice from highly qualified professionals and have made your decisions without reliance on MoneyFlap.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">MoneyFlap does not provide investment or tax advice or exercise any investment discretion on your behalf.  Nothing on Website is an offer to sell, a solicitation of an offer to buy, or a recommendation for any Virtual Asset by MoneyFlap.</p></li>
                </ul>
                <h3 class="text-white">Not a bank, broker-dealer, or regulated financial institution</h3>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You should note that your account balances may not be considered or called “deposits”, as the regulated financial institutions, especially banks or credit institutions may be using the term. MoneyFlap is not and does not pretend to be a bank or regulated financial institution under the United States Federal Law or under any other jurisdiction laws.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You should note that the Tokenized Financial Assets that MoneyFlap facilitates the accessibility may not be considered as a listing or selling of “Securities” or an offering of a “brokerage account”, as the regulated brokerage may be using the term. MoneyFlap is not and does not pretend to be a broker-dealer or a trust registered under the United States Federal Law or under any other jurisdiction laws.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You should note that your account balances are not subject to deposit insurance protection of any regulatory scheme, including the Federal Deposit Insurance Corporation (FDIC), as well as any securities investor protection, including the Securities Investor Protection Corporation (SIPC).</p></li>
                </ul>
                <h3 class="text-white">Account Security</h3>
                <p class="text-white">You are responsible for maintaining the confidentiality of the username and password that you designate during the registration process, and you are fully responsible for all activities that occur under your username and password. You agree to (a) immediately notify MoneyFlap of any unauthorized use of your username or password or any other breach of security, and (b) ensure that you exit from your account at the end of each session. MoneyFlap will not be liable for any loss or damage arising from your failure to comply with this provision. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. If you share your computer with others, you may wish to consider disabling your auto-login feature if you have it linked to your MoneyFlap account.</p>
                <h3 class="text-white">Your Use of the Websites</h3>
                <p class="text-white">You are responsible for maintaining the confidentiality of the username and password that you designate during the registration process, and you are fully responsible for all activities that occur under your username and password. You agree to (a) immediately notify MoneyFlap of any unauthorized use of your username or password or any other breach of security, and (b) ensure that you exit from your account at the end of each session. MoneyFlap will not be liable for any loss or damage arising from your failure to comply with this provision. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. If you share your computer with others, you may wish to consider disabling your auto-login feature if you have it linked to your MoneyFlap account.</p>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You should note that your account balances may not be considered or called “deposits”, as the regulated financial institutions, especially banks or credit institutions may be using the term. MoneyFlap is not and does not pretend to be a bank or regulated financial institution under the United States Federal Law or under any other jurisdiction laws.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You should note that the Tokenized Financial Assets that MoneyFlap facilitates the accessibility may not be considered as a listing or selling of “Securities” or an offering of a “brokerage account”, as the regulated brokerage may be using the term. MoneyFlap is not and does not pretend to be a broker-dealer or a trust registered under the United States Federal Law or under any other jurisdiction laws.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You should note that your account balances are not subject to deposit insurance protection of any regulatory scheme, including the Federal Deposit Insurance Corporation (FDIC), as well as any securities investor protection, including the Securities Investor Protection Corporation (SIPC).</p></li>
                </ul>
                <h3 class="text-white">Representations and Warranties</h3>
                <p class="text-white">You hereby represent and warrant to MoneyFlap as follows:</p>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You should note that your account balances may not be considered or called “deposits”, as the regulated financial institutions, especially banks or credit institutions may be using the term. MoneyFlap is not and does not pretend to be a bank or regulated financial institution under the United States Federal Law or under any other jurisdiction laws.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You should note that the Tokenized Financial Assets that MoneyFlap facilitates the accessibility may not be considered as a listing or selling of “Securities” or an offering of a “brokerage account”, as the regulated brokerage may be using the term. MoneyFlap is not and does not pretend to be a broker-dealer or a trust registered under the United States Federal Law or under any other jurisdiction laws.</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You should note that your account balances are not subject to deposit insurance protection of any regulatory scheme, including the Federal Deposit Insurance Corporation (FDIC), as well as any securities investor protection, including the Securities Investor Protection Corporation (SIPC).</p></li>
                </ul>
                <h3 class="text-white">Term, Suspension, and Termination</h3>
                <p class="text-white ml-1">This Agreement will remain in full force and effect while you use the Websites and/or Service. You may terminate this agreement and/or the use of the MoneyFlap Services at any time by closing your MoneyFlap Account. If you terminate this agreement or close your MoneyFlap Account, to help MoneyFlap analyze and improve the Service, you may be asked to provide a reason for your closure/termination. However, MoneyFlap reserves the right to cancel your request to close your account due to regulatory and compliance obligations.
MoneyFlap may suspend, limit, or terminate your account for any reason by sending notice to you at the email address you provide in your account registration, or such other email address as you may later provide to MoneyFlap. Without any liability and at any time, MoneyFlap may suspend, limit, or terminate your use of MoneyFlap Services, or your access to your MoneyFlap account if:</p>
                <ul style="list-style-type: none;">
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You have breached these Terms of Service, Terms and Conditions, and any Applicable Laws;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You hold an account that is undergoing financial crime investigations or legal proceedings;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You hold an account that is non-compliant and is considered high-risk by the regulatory guidelines;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You hold an account that is involved in any Prohibited Businesses or Activities as per these Terms of Service;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You hold an account that is subject to a security compromise or breach, and a transaction or order is erroneous;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You hold an account that is subject to unauthorized or fraudulent access or is accessed without your consent and approval;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">You hold an account that is red-flagged as suspicious, and linked to money laundering, terrorist financing, fraudulent activities, or any “bad user” scenarios covered by our Anti-Money Laundering (AML) policy;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">MoneyFlap is subject to maintenance of our infrastructure, including the systems of our third-party partners;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">MoneyFlap is reassessing the eligibility criteria for opening an account or accessibility of our Services;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">MoneyFlap is entitled to comply with legislation, regulatory and judicial orders, or governmental amendments;</p></li>
                    <li class="text-white"><img src="../src/assets/icon-compliance.svg"/><p class="d-inline">MoneyFlap is fixing defaillances in any information technology system (IT system) related to the provision of our Services;</p></li>
                </ul>
                <p class="text-white">All decisions regarding the termination of accounts shall be made at the sole discretion of MoneyFlap. MoneyFlap is not required to provide you notice before suspending, limiting, and terminating your account. MoneyFlap is not required and may be prohibited, from disclosing a reason for the termination of your account. Even after your account is terminated, this Agreement will remain in effect. All terms that by their nature may survive termination of this Agreement shall be deemed to survive such termination.</p>
                <h3 class="text-white">Modifications to Service</h3>
                <p class="text-white">MoneyFlap reserves the right at any time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that MoneyFlap shall not be liable to you or any third party for any modification, suspension, or discontinuance of the Service.</p>
                <h3 class="text-white">Blocking of IP Addresses</h3>
                <p class="text-white">To protect the integrity of the Services, MoneyFlap reserves the right at any time in its sole discretion to block Clients from certain IP addresses from accessing the Websites.</p>









                <h3 class="text-white">Contact:</h3>
                <p class="text-white ml-1">Proprietary Rights</p><p class="text-white">
MoneyFlap retains all proprietary rights in the Websites and the Service. The Website contains the copyrighted material, trademarks, and other proprietary information of MoneyFlap, and its licensors. Except where we have given you express written permission, you may not copy, modify, publish, transmit, distribute, perform, display, or sell any such proprietary information. All content on MoneyFlap is proprietary. Except where otherwise specified in this Agreement, all Content is the copyrighted material of MoneyFlap and for MoneyFlap’s Clients' use only. Distribution of Content to others is strictly prohibited. You agree that MoneyFlap would be irreparably harmed by any violation or threatened violation of this section and that, therefore, MoneyFlap shall be entitled to an injunction prohibiting you from any violation or threatened violation of this section, without posting bond, in addition to any other right or remedy it may have.
We may provide links to third-party websites, and some of the content appearing on MoneyFlap may be supplied by third parties. MoneyFlap has no responsibility for these third-party websites nor for their content, which is subject to and governed by the Terms of Service and/or privacy policies, if any, of the applicable third-party content providers.</p>
                <p class="text-white">Ownership of Your Content; Licenses
You agree that any content you upload to the Websites and/or the Service (“Your Content”) shall become the property of MoneyFlap. This shall not affect Sections (Copyright Policy), (Limitation of Liability), and (Indemnity by You) of this Agreement.
However, concerning Your Content, MoneyFlap grants you a worldwide, royalty-free, and non-exclusive license(s) to use, distribute, reproduce, and publicly display such content, except for commercial or for-profit use accounts.
Any Content other than Your Content is the property of the relevant Uploader and is or may be subject to copyright, trademark rights, or other intellectual property or proprietary rights. Such Content may not be downloaded, reproduced, distributed, transmitted, re-uploaded, republished, displayed, sold, licensed, made available or otherwise communicated to the public or exploited for any purposes except via the features of the Websites from time to time and within the parameters set by the Uploader on the Service or with the express written consent of the Uploader. Where you repost another user's Content, or include another user's Content in a set, you acquire no ownership rights whatsoever in that Content. Subject to the rights expressly granted in this section, all rights in Content are reserved to the relevant Uploader.</p>
                
            </div>
        </div>
    </NuxtLayout>
</template>
